### ISSUE TITLE
vinkla/hashids ~1.0 -> no matching package found

### ISSUE THREAD

**Issue by PanosSynetos** [naabster/laravel-eloquent-hashids#1]
Hello @naabster .

Your package requires `vinkla/hashids ~1.0` which is not the correct one for Laravel 5

`"vinkla/hashids": "^2.0"` is the correct one for laravel 5

You could also change the link in the homepage that points to vinklas repository? You point to the Laravel 4 version

**Comment by naabster** [comment]
thanks, I have updated the requirments.
