### ISSUE TITLE
Unable to get uid to show up when retrieving model object

### ISSUE THREAD

**Issue by abodnar** [naabster/laravel-eloquent-hashids#2]
I installed the package and added the use for the namespacing and trait to my Eloquent model and when I go into artisan tinker and run App\Obj::find(1). I get the model, but there is no uid field.

I have not overwritten any of getHashid functions as the defaults are fine with me and I'm currently running Laravel 5.2.

Any suggestions on how to get this to work?

**Comment by naabster** [comment]
Sorry for the late answer - did you add your column to your table (with an db migration)?
That part is missing from the readme. I will add this info..

**Comment by abodnar** [comment]
I honestly don't remember and I went with a different solution.

Thanks for responding though.
