### ISSUE TITLE
Opinionated contexts

### ISSUE THREAD

**Issue by mikerockett** [naabster/laravel-eloquent-hashids#7]
It's a good thing that the package supports multiple contexts for different models, but I don't think it should be forced. I think that the default connection should be used, unless overridden by the model itself.

In the app I'm building at the moment, there are 13 models that need hashids, but do not need them to be contextualised. Only main models, such as those for users, client accounts, invoices, and receipts require contextualisation. For those 13, I feel it is tedious to have to specify the main connection.

Perhaps a property could be added to traited models that overrides the behaviour.

```php
protected $hashIdContextual = true; // defaults to false
```

When set, the `table.*` connection would be used. Otherwise, revert to default, as specified by configuration value `hashids.default`.

The alternative would be to reverse this to prevent breaking changes on existing installations:

```php
protected $hashIdContextual = false; // defaults to true
```

In this case, setting the property on the model class is better than specifying the entire method override. Sure, this could be done by additional trait, but that seems overkill to me, giving consideration to the fact that the package is opinionated.

Does this look feasible?

**Comment by joelcuevas** [comment]
Agree.
